server:
  port: ${GATEWAY_PORT:8765}

spring:
  application:
    name: gateway-server


security.ignored: /**

zuul:
  routes:
    functions:
      path: /functions-api/**
      sensitiveHeaders:
      serviceId: functions-service
    workflow:
      path: /workflows-api/**
      sensitiveHeaders:
      serviceId: workflow-api
      #stripPrefix: true
    scheduler:
      path: /scheduler/**
      sensitiveHeaders:
      serviceId: scheduler
    idntity:
      path: /uaa/**
      sensitiveHeaders:
      serviceId: auth-service
    executor:
      path: /workflow-executor-api/**
      sensitiveHeaders:
      serviceId: workflow-executor

# Increase the Hystrix timeout to 10s (globally)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
        timeout:
          enabled: false


ribbon:
  maxAutoRetries: 3
  MaxAutoRetriesNextServer: 3
  OkToRetryOnAllOperations: true
  ReadTimeout: 5000
  ConnectTimeout: 3000


eureka:
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


#proxy:
#  auth:
#    routes:
#      functions: oauth2
#      workflow: oauth2
#      identity: passthru